version: "3"

services: 
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on: 
      - database
  database:
    build: ./db
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start --insecure --store=endpoints_db
  db-builder:
    image: cockroachdb/cockroach
    volumes: 
      - ./db:/db
    working_dir: /db
    entrypoint: "/bin/bash"
    command: ./setup_db.sh
    depends_on: 
      - database